services:
  db:
    image: postgres:17-alpine
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: no_crypto_mining_user
      POSTGRES_PASSWORD: no_crypto_mining_password

volumes:
  db-volume:
